# Category

CATEGORY = type("CATEGORY", (), {})

CATEGORY.NONE:str = ""
CATEGORY.PHYSICAL:str = "Physical"
CATEGORY.SPECIAL:str = "Special"
CATEGORY.STATUS:str = "Status"

# Experience Groups

GROUP = type("GROUP", (), {})

GROUP.MEDIUM_FAST = "Medium Fast"
GROUP.ERATIC = "Eratic"
GROUP.FLUCTUATING = "Fluctuating"
GROUP.MEDIUM_SLOW = "Medium Slow"
GROUP.FAST = "Fast"
GROUP.SLOW = "Slow"

# Stats

STATS = type("STATS", (), {})
STATS.HP = "HP"
STATS.ATTACK = "ATK"
STATS.DEFENSE = "DEF"
STATS.SPECIAL_ATTACK = "SP.ATK"
STATS.SPECIAL_DEFENSE = "SP.DEF"
STATS.SPEED = "SPD"

# Nature

NATURE = type("NATURE", (), {})

NATURE.HARDY = "Hardy"
NATURE.LONELY = "Lonely"
NATURE.BRAVE = "Brave"
NATURE.ADAMANT = "Adamant"
NATURE.NAUGHTY = "Naughty"
NATURE.BOLD = "Bold"
NATURE.DOCILE = "Docile"
NATURE.RELAXED = "Relaxed"
NATURE.IMPISH = "Impish"
NATURE.LAX = "Lax"
NATURE.TIMID = "Timid"
NATURE.HASTY = "Hasty"
NATURE.SERIOUS = "Serious"
NATURE.JOLLY = "Jolly"
NATURE.NAIVE = "Naive"
NATURE.MODEST = "Modest"
NATURE.MILD = "Mild"
NATURE.QUIET = "Quiet"
NATURE.BASHFUL = "Bashful"
NATURE.RASH = "Rash"
NATURE.CALM = "Calm"
NATURE.GENTLE = "Gentle"
NATURE.SASSY = "Sassy"
NATURE.CAREFUL = "Careful"
NATURE.QUIRKY = "Quirky"

NATURE_LIST = [getattr(NATURE, attr) for attr in dir(NATURE) if not callable(getattr(NATURE, attr)) and not attr.startswith("__")]

NATURE_TABLE = {
    NATURE.HARDY: {STATS.ATTACK: 1, STATS.DEFENSE: 1, STATS.SPECIAL_ATTACK: 1, STATS.SPECIAL_DEFENSE: 1, STATS.SPEED: 1},
    
    NATURE.LONELY: {STATS.ATTACK: 1.1, STATS.DEFENSE: 0.9, STATS.SPECIAL_ATTACK: 1, STATS.SPECIAL_DEFENSE: 1, STATS.SPEED: 1},
    
    NATURE.BRAVE: {STATS.ATTACK: 1.1, STATS.DEFENSE: 1, STATS.SPECIAL_ATTACK: 1, STATS.SPECIAL_DEFENSE: 1, STATS.SPEED: 0.9},
    
    NATURE.ADAMANT: {STATS.ATTACK: 1.1, STATS.DEFENSE: 1, STATS.SPECIAL_ATTACK: 0.9, STATS.SPECIAL_DEFENSE: 1, STATS.SPEED: 1},
    
    NATURE.NAUGHTY: {STATS.ATTACK: 1.1, STATS.DEFENSE: 1, STATS.SPECIAL_ATTACK: 1, STATS.SPECIAL_DEFENSE: 0.9, STATS.SPEED: 1},
    
    NATURE.BOLD: {STATS.ATTACK: 0.9, STATS.DEFENSE: 1.1, STATS.SPECIAL_ATTACK: 1, STATS.SPECIAL_DEFENSE: 1, STATS.SPEED: 1},
    
    NATURE.DOCILE: {STATS.ATTACK: 1, STATS.DEFENSE: 1, STATS.SPECIAL_ATTACK: 1, STATS.SPECIAL_DEFENSE: 1, STATS.SPEED: 1},
    
    NATURE.RELAXED: {STATS.ATTACK: 1, STATS.DEFENSE: 1.1, STATS.SPECIAL_ATTACK: 1, STATS.SPECIAL_DEFENSE: 1, STATS.SPEED: 0.9},
    
    NATURE.IMPISH: {STATS.ATTACK: 1, STATS.DEFENSE: 1.1, STATS.SPECIAL_ATTACK: 0.9, STATS.SPECIAL_DEFENSE: 1, STATS.SPEED: 1},
    
    NATURE.LAX: {STATS.ATTACK: 1, STATS.DEFENSE: 1.1, STATS.SPECIAL_ATTACK: 1, STATS.SPECIAL_DEFENSE: 0.9, STATS.SPEED: 1},
    
    NATURE.TIMID: {STATS.ATTACK: 0.9, STATS.DEFENSE: 1, STATS.SPECIAL_ATTACK: 1, STATS.SPECIAL_DEFENSE: 1, STATS.SPEED: 1.1},
    
    NATURE.HASTY: {STATS.ATTACK: 1, STATS.DEFENSE: 0.9, STATS.SPECIAL_ATTACK: 1, STATS.SPECIAL_DEFENSE: 1, STATS.SPEED: 1.1},
    
    NATURE.SERIOUS: {STATS.ATTACK: 1, STATS.DEFENSE: 1, STATS.SPECIAL_ATTACK: 1, STATS.SPECIAL_DEFENSE: 1, STATS.SPEED: 1},
    
    NATURE.JOLLY: {STATS.ATTACK: 1, STATS.DEFENSE: 1, STATS.SPECIAL_ATTACK: 0.9, STATS.SPECIAL_DEFENSE: 1, STATS.SPEED: 1.1},
    
    NATURE.NAIVE: {STATS.ATTACK: 1, STATS.DEFENSE: 1, STATS.SPECIAL_ATTACK: 1, STATS.SPECIAL_DEFENSE: 0.9, STATS.SPEED: 1.1},
    
    NATURE.MODEST: {STATS.ATTACK: 0.9, STATS.DEFENSE: 1, STATS.SPECIAL_ATTACK: 1.1, STATS.SPECIAL_DEFENSE: 1, STATS.SPEED: 1},
    
    NATURE.MILD: {STATS.ATTACK: 1, STATS.DEFENSE: 0.9, STATS.SPECIAL_ATTACK: 1.1, STATS.SPECIAL_DEFENSE: 1, STATS.SPEED: 1},
    
    NATURE.QUIET: {STATS.ATTACK: 1, STATS.DEFENSE: 1, STATS.SPECIAL_ATTACK: 1.1, STATS.SPECIAL_DEFENSE: 1, STATS.SPEED: 0.9},
    
    NATURE.BASHFUL: {STATS.ATTACK: 1, STATS.DEFENSE: 1, STATS.SPECIAL_ATTACK: 1, STATS.SPECIAL_DEFENSE: 1, STATS.SPEED: 1},
    
    NATURE.RASH: {STATS.ATTACK: 1, STATS.DEFENSE: 1, STATS.SPECIAL_ATTACK: 1.1, STATS.SPECIAL_DEFENSE: 0.9, STATS.SPEED: 1},
    
    NATURE.CALM: {STATS.ATTACK: 0.9, STATS.DEFENSE: 1, STATS.SPECIAL_ATTACK: 1, STATS.SPECIAL_DEFENSE: 1.1, STATS.SPEED: 1},
    
    NATURE.GENTLE: {STATS.ATTACK: 1, STATS.DEFENSE: 0.9, STATS.SPECIAL_ATTACK: 1, STATS.SPECIAL_DEFENSE: 1.1, STATS.SPEED: 1},
    
    NATURE.SASSY: {STATS.ATTACK: 1, STATS.DEFENSE: 1, STATS.SPECIAL_ATTACK: 1, STATS.SPECIAL_DEFENSE: 1.1, STATS.SPEED: 0.9},
    
    NATURE.CAREFUL: {STATS.ATTACK: 1, STATS.DEFENSE: 1, STATS.SPECIAL_ATTACK: 0.9, STATS.SPECIAL_DEFENSE: 1.1, STATS.SPEED: 1},
    
    NATURE.QUIRKY: {STATS.ATTACK: 1, STATS.DEFENSE: 1, STATS.SPECIAL_ATTACK: 1, STATS.SPECIAL_DEFENSE: 1, STATS.SPEED: 1},
}